# Generated by Django 5.0.4 on 2024-04-14 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quota',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
