# Generated by Django 5.0.4 on 2024-04-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_transcription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionsubmission',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date submitted'),
        ),
    ]
