FROM python:3
WORKDIR /backend
RUN apt update
RUN apt install ffmpeg -y
COPY ./requirements.txt ./requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . .
CMD ["python", "-u", "manage.py", "runserver", "0.0.0.0:8000"]