services:
  s2_worker:
    tty: true
    network_mode: "host"
    build:
      context: "${S2_WORKER_DIR}"

    environment:
      - "RABBITMQ_USERNAME=${RABBITMQ_USERNAME}"
      - "RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}"
      - "REQUESTS_QUEUE_EXTERNAL_URL=172.187.216.231"
      - "REQUESTS_QUEUE_EXTERNAL_PORT=${REQUESTS_QUEUE_EXTERNAL_PORT}"
      - "OUTPUT_EXTENSION=${S2_WORKER_OUTPUT_EXTENSION}"
      - "SUBMITTED_FILE_ROOT=${S2_WORKER_SUBMITTED_FILE_ROOT}"
      - "OUTPUT_FILE_ROOT=${S2_WORKER_OUTPUT_FILE_ROOT}"
      - "SUBMISSION_QUEUE_NAME=${SUBMISSION_QUEUE_NAME}"
      - "RESULTS_QUEUE_NAME=${RESULTS_QUEUE_NAME}"

    restart: always
